#pragma config(Sensor, S2,     frontSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

int speedLeft = 0;
int speedRight = 0;
	while(SensorValue(frontSensor) == 0)
	{

		motor(left) = speedLeft;
		motor(right) = speedRight;
		wait1Msec(1000);

	speedLeft = speedLeft + 10;
	speedRight = speedRight + 5;
	}


}
