#pragma config(Sensor, S2,     frontSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while(true)
{
	while(SensorValue(frontSensor) == 0)
	{
		motor(left) = 50;
		motor(right) = 50;
	}

	motor(left) = -45;
	motor(right) = -45;
	wait1Msec(1900);

	motor(left) = 0;
	motor(right) = 45;
	wait1Msec(1000);


	while(SensorValue(frontSensor) == 0)
	{
		motor(left) = 50;
		motor(right) = 45;

	}


}



}
